---
Name: foxystripe-mailchimp
After:
  - 'foxystripe/*'
---
Dynamic\FoxyStripe\Controller\FoxyStripeController:
  extensions:
    - Dynamic\FoxyStripeMailChimp\ORM\FoxyStripeMailChimpExtension
Dynamic\FoxyStripe\Model\FoxyStripeSetting:
  extensions:
    - Dynamic\FoxyStripeMailChimp\ORM\FoxyStripeMailChimpSettingExtension
SilverStripe\Admin\LeftAndMain:
  extensions:
    - Dynamic\FoxyStripeMailChimp\ORM\FoxyStripeMailChimpLeftAndMain
Dynamic\FoxyStripeMailChimp\ORM\FoxyStripeMailChimpExtension:
  use_custom_field: true
  custom_field_name: newsletter_subscribe
  custom_field_value: 1
  double_opt_in: false
