---
Name: foxystripe-mailchimp
---
FoxyStripe_Controller:
  extensions:
    - FoxyStripeMailChimpExtension

FoxyStripeMailChimpExtension:
  use_custom_field: true
  custom_field_name: 'newsletter_subscribe'
  custom_field_value: 1
  double_opt_in: false

