---
Name: foxystripe-mailchimp
After:
  - 'foxystripe/*'
---
FoxyStripe_Controller:
  extensions:
    - FoxyStripeMailChimpExtension

SiteConfig:
  extensions:
    # would get duplicate tabs if this wasn't done (after seems to be failing or something)
    - FoxyStripeSiteConfig
    - FoxyStripeMailChimpSiteConfig

LeftAndMain:
  extensions:
    - FoxyStripeMailChimpLeftAndMain

FoxyStripeMailChimpExtension:
  use_custom_field: true
  custom_field_name: 'newsletter_subscribe'
  custom_field_value: 1
  double_opt_in: false

